# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'house_datas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import requests
import app

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 370)
        self.House_Datas_Label = QtWidgets.QLabel(Form)
        self.House_Datas_Label.setGeometry(QtCore.QRect(60, 10, 261, 91))
        self.House_Datas_Label.setObjectName("House_Datas_Label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(120, 120, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Logout_LinkButton = QtWidgets.QCommandLinkButton(Form)
        self.Logout_LinkButton.setGeometry(QtCore.QRect(270, 330, 101, 41))
        self.Logout_LinkButton.setObjectName("Logout_LinkButton")
        self.Back_Home_Button = QtWidgets.QPushButton(Form)
        self.Back_Home_Button.setGeometry(QtCore.QRect(10, 330, 121, 31))
        self.Back_Home_Button.setObjectName("Back_Home_Button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Connect the logout button to the logout function
        self.Logout_LinkButton.clicked.connect(self.logout_and_redirect)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.House_Datas_Label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">House Datas</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "Add"))
        self.comboBox.setItemText(1, _translate("Form", "Delete"))
        self.comboBox.setItemText(2, _translate("Form", "Modify"))
        self.comboBox.setItemText(3, _translate("Form", "Query"))
        self.Logout_LinkButton.setText(_translate("Form", "Logout"))
        self.Back_Home_Button.setText(_translate("Form", "Back Home"))
    
    def logout_and_redirect(self):
        # 發送GET請求給Flask應用程式的/logout路由
        try:
            response = requests.get('http://127.0.0.1:5000/logout')
            if response.status_code == 200:
                # 如果成功登出，將自動關閉視窗
                QtWidgets.QApplication.instance().quit()    # 關閉pyqt應用程式
                # Restart the application to show the login page
                QtCore.QProcess.startDetached(sys.executable, sys.argv)
        except requests.exceptions.RequestException as e:
            print(f"Error: {e}")

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
