# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_control_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
import sys
from users import Ui_Form as Ui_Users_Form
from room_datas import Ui_Form as Ui_Room_Datas_Form
from house_datas import Ui_Form as Ui_House_Datas_Form
import requests
import app

class Ui_Main_Control_Panel_Form(object):
    def setupUi(self, Main_Control_Panel_Form):
        Main_Control_Panel_Form.setObjectName("Main_Control_Panel_Form")
        Main_Control_Panel_Form.resize(375, 374)
        self.Main_Control_Panel_Label = QtWidgets.QLabel(Main_Control_Panel_Form)
        self.Main_Control_Panel_Label.setGeometry(QtCore.QRect(50, 10, 261, 91))
        self.Main_Control_Panel_Label.setObjectName("Main_Control_Panel_Label")
        self.Users_Button = QtWidgets.QPushButton(Main_Control_Panel_Form)
        self.Users_Button.setGeometry(QtCore.QRect(110, 110, 151, 51))
        self.Users_Button.setObjectName("Users_Button")
        self.Room_Datas_Button = QtWidgets.QPushButton(Main_Control_Panel_Form)
        self.Room_Datas_Button.setGeometry(QtCore.QRect(110, 190, 151, 51))
        self.Room_Datas_Button.setObjectName("Room_Datas_Button")
        self.House_Datas_Button = QtWidgets.QPushButton(Main_Control_Panel_Form)
        self.House_Datas_Button.setGeometry(QtCore.QRect(110, 270, 151, 51))
        self.House_Datas_Button.setObjectName("House_Datas_Button")
        self.Logout_LinkButton = QtWidgets.QCommandLinkButton(Main_Control_Panel_Form)
        self.Logout_LinkButton.setGeometry(QtCore.QRect(270, 330, 101, 41))
        self.Logout_LinkButton.setObjectName("Logout_LinkButton")

        self.retranslateUi(Main_Control_Panel_Form)
        QtCore.QMetaObject.connectSlotsByName(Main_Control_Panel_Form)

    def retranslateUi(self, Main_Control_Panel_Form):
        _translate = QtCore.QCoreApplication.translate
        Main_Control_Panel_Form.setWindowTitle(_translate("Main_Control_Panel_Form", "Form"))
        self.Main_Control_Panel_Label.setText(_translate("Main_Control_Panel_Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Main Control Panel</span></p></body></html>"))
        self.Users_Button.setText(_translate("Main_Control_Panel_Form", "Users"))
        self.Room_Datas_Button.setText(_translate("Main_Control_Panel_Form", "Room Data"))
        self.House_Datas_Button.setText(_translate("Main_Control_Panel_Form", "House Datas"))
        self.Logout_LinkButton.setText(_translate("Main_Control_Panel_Form", "Logout"))
    
class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        self.centralWidget = QtWidgets.QStackedWidget()
        self.setCentralWidget(self.centralWidget)

        # main control panel form
        self.main_control_panel_form = QtWidgets.QWidget()
        self.ui_main_control_panel = Ui_Main_Control_Panel_Form()
        self.ui_main_control_panel.setupUi(self.main_control_panel_form)
        self.centralWidget.addWidget(self.main_control_panel_form)

        # users form
        self.users_form = QtWidgets.QWidget()
        self.ui_users_form = Ui_Users_Form()
        self.ui_users_form.setupUi(self.users_form)
        self.centralWidget.addWidget(self.users_form)

        # room datas form
        self.room_datas_form = QtWidgets.QWidget()
        self.ui_room_datas_form = Ui_Room_Datas_Form()
        self.ui_room_datas_form.setupUi(self.room_datas_form)
        self.centralWidget.addWidget(self.room_datas_form)

        # house datas form
        self.house_datas_form = QtWidgets.QWidget()
        self.ui_house_datas_form = Ui_House_Datas_Form()
        self.ui_house_datas_form.setupUi(self.house_datas_form)
        self.centralWidget.addWidget(self.house_datas_form)

        # connect buttons to methods
        self.ui_main_control_panel.Users_Button.clicked.connect(self.show_users_page)
        self.ui_users_form.Back_Home_Button.clicked.connect(self.show_main_control_panel)
        self.ui_main_control_panel.Room_Datas_Button.clicked.connect(self.show_room_datas_page)
        self.ui_room_datas_form.Back_Home_Button.clicked.connect(self.show_main_control_panel)
        self.ui_main_control_panel.House_Datas_Button.clicked.connect(self.show_house_datas_page)
        self.ui_house_datas_form.Back_Home_Button.clicked.connect(self.show_main_control_panel)
        self.ui_main_control_panel.Logout_LinkButton.clicked.connect(self.logout_and_redirect)
    
    def logout_and_redirect(self):
        # 發送GET請求給Flask應用程式的/logout路由
        try:
            response = requests.get('http://127.0.0.1:5000/logout')
            if response.status_code == 200:
                # 如果成功登出，將自動關閉視窗
                QtWidgets.QApplication.instance().quit()    # 關閉pyqt應用程式
                # Restart the application to show the login page
                QtCore.QProcess.startDetached(sys.executable, sys.argv)
        except requests.exceptions.RequestException as e:
            print(f"Error: {e}")

    def show_house_datas_page(self):
        self.centralWidget.setCurrentWidget(self.house_datas_form)
    
    def show_room_datas_page(self):
        self.centralWidget.setCurrentWidget(self.room_datas_form)
    
    def show_users_page(self):
        self.centralWidget.setCurrentWidget(self.users_form)

    def show_main_control_panel(self):
        self.centralWidget.setCurrentWidget(self.main_control_panel_form)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
