# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'room_datas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import requests
import app
import add_room_data, delete_room_data, modify_room_data, query_room_data

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(372, 371)
        self.Room_Datas_Label = QtWidgets.QLabel(Form)
        self.Room_Datas_Label.setGeometry(QtCore.QRect(60, 10, 261, 91))
        self.Room_Datas_Label.setObjectName("Room_Datas_Label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(120, 110, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Logout_LinkButton = QtWidgets.QCommandLinkButton(Form)
        self.Logout_LinkButton.setGeometry(QtCore.QRect(270, 330, 101, 41))
        self.Logout_LinkButton.setObjectName("Logout_LinkButton")
        self.Back_Home_Button = QtWidgets.QPushButton(Form)
        self.Back_Home_Button.setGeometry(QtCore.QRect(10, 330, 121, 31))
        self.Back_Home_Button.setObjectName("Back_Home_Button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Connect the logout button to the logout function
        self.Logout_LinkButton.clicked.connect(self.logout_and_redirect)

        # Connect the comboBox selection change to a function
        self.comboBox.currentIndexChanged.connect(self.handle_combobox_change)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Room_Datas_Label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Room Datas</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "Add"))
        self.comboBox.setItemText(1, _translate("Form", "Delete"))
        self.comboBox.setItemText(2, _translate("Form", "Modify"))
        self.comboBox.setItemText(3, _translate("Form", "Query"))
        self.Logout_LinkButton.setText(_translate("Form", "Logout"))
        self.Back_Home_Button.setText(_translate("Form", "Back Home"))
    
    def handle_combobox_change(self, index):
        print(f"ComboBox index changed to {index}") # debug output
        if index == 0:  # "Add" option
            self.add_room_data_prompt()
        elif index == 1:    # "Delete" option
            self.delete_room_data_prompt()
        elif index == 2:    # "Modify" option
            self.modify_room_data_prompt()
        elif index == 3:    # "Query" option
            self.query_room_data_prompt()
    
    def query_room_data_prompt(self):
        print("query_room_data_prompt called")
        choice, ok = QtWidgets.QInputDialog.getText(None, 'Input Dialog', 'Enter choice:')
        print(f"Choice entered: {choice}, ok: {ok}")  # debug output
        if ok:
            query_room_data.query_room_data(choice)
    
    def modify_room_data_prompt(self):
        print("modify_room_data_prompt called")
        filename, ok1 = QtWidgets.QInputDialog.getText(None, 'Input Dialog', 'Enter filename:')
        print(f"Filename entered: {filename}, ok1: {ok1}")  # debug output
        if ok1:
            new_filename, ok2 = QtWidgets.QInputDialog.getText(None, 'Input Dialog', 'Enter new_filename:')
            print(f"New_filename entered: {new_filename}, ok2: {ok2}")  # debug output
            if ok2:
                modify_room_data.modify_room_data(filename, new_filename)
    
    def delete_room_data_prompt(self):
        print("delete_room_data_prompt called")
        filename, ok = QtWidgets.QInputDialog.getText(None, 'Input Dialog', 'Enter filename:')
        print(f"Filename entered: {filename}, ok: {ok}")  # debug output
        if ok:
            delete_room_data.delete_room_data(filename)
    
    def add_room_data_prompt(self):
        print("add_room_data_prompt called")
        filename, ok = QtWidgets.QInputDialog.getText(None, 'Input Dialog', 'Enter filename:')
        print(f"Filename entered: {filename}, ok: {ok}")  # debug output
        if ok:
            add_room_data.add_room_data(filename)
    
    def logout_and_redirect(self):
        # 發送GET請求給Flask應用程式的/logout路由
        try:
            response = requests.get('http://127.0.0.1:5000/logout')
            if response.status_code == 200:
                # 如果成功登出，將自動關閉視窗
                QtWidgets.QApplication.instance().quit()    # 關閉pyqt應用程式
                # Restart the application to show the login page
                QtCore.QProcess.startDetached(sys.executable, sys.argv)
        except requests.exceptions.RequestException as e:
            print(f"Error: {e}")

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
